### ISSUE TITLE
Deprecate Old NPM package

### ISSUE THREAD

**Issue by rfearing** [chiedolabs/eslint-config-node#9]
Both: 

* https://www.npmjs.com/package/eslint-config-chiedo-labs-node
* https://www.npmjs.com/package/@chiedolabs/eslint-config-node

Should not live side by side. The first should be deprecated.

Example:. https://www.npmjs.com/package/eslint-config-chiedo-labs-nextjs

**Comment by chiedo** [comment]
Done
